[Amazon Review Required] ALMS-203 [iOS] Update quickstart app to use latest versions of Auth and Tracking SDKs
aws-geospatial/amazon-location-samples-ios pull request #3
Opened 2024-07-01 14:54 UTC by zeeshanmakeen

2024-07-08 18:55 UTC, cgalvan approved these changes
Nitpick: I would change this to using WIP new version vs. latest version of SDK, since they are pointing to branches on a fork, instead of the actual repo for those SDKs.

2024-07-22 18:03 UTC, mbalfour-amzn commented
Going forward, please put "Extended team WIP" as a label instead of in the title. Thanks!

2024-10-03 18:18 UTC, mbalfour-amzn requested changes

2024-10-03 18:18 UTC, mbalfour-amzn commented on tracking-with-geofence-notifications/AWSLocationSampleApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +      }
These should be coming from aws-geospatial, not makeen-project

2024-11-01 20:16 UTC, cgalvan commented
Closing this in favor of https://github.com/aws-geospatial/amazon-location-samples-ios/pull/4

2024-11-01 20:16 UTC, closed without merging